# Generated by Django 2.0.7 on 2018-07-15 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20180715_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 10, 56, 38, 187334, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='fri',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/21(金)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='mon',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/24(月)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='satur',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/22(土)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sun',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/23(日)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='thurs',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/20(木)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tues',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/25(火)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='wens',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/19(水)'),
        ),
    ]
