# Generated by Django 2.0.7 on 2018-07-15 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20180715_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal',
            field=models.TextField(default='特になし。', verbose_name='所感,次週までの感想'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 11, 31, 43, 649629, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='fri',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/13(金)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='mon',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/16(月)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='satur',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/14(土)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sun',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/15(日)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='thurs',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/12(木)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='tues',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/17(火)'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='wens',
            field=models.CharField(default='なし', max_length=100, verbose_name='7/11(水)'),
        ),
    ]
