# Generated by Django 2.0.7 on 2018-07-15 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_auto_20180715_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 12, 30, 28, 296065, tzinfo=utc), verbose_name='作成日'),
        ),
    ]
