# Generated by Django 2.0.7 on 2018-07-15 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20180715_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 7, 15, 13, 26, 55, 827827, tzinfo=utc), verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal',
            field=models.TextField(default='特になし。', verbose_name='所感,次週への感想'),
        ),
    ]
